### ISSUE TITLE
Addon does not load for german client

### ISSUE THREAD

**Issue by babylonlin** [RestedXP/RXPGuides#51] opened 2022-09-04 07:56 UTC
Lua error for client wotlk classic if I try to load the addon for german client

**Comment by SabreValkyrn** [comment] 2022-09-05 05:07
What is the lua error?

Are you on v4.2.11?

**Comment by babylonlin** [comment] 2022-09-05 12:35
Lua error (this happens if I set the language to German. English client is fine):

Message: Interface\AddOns\RXPGuides\RXPGuides.lua:738: attempt to call field 'UpdateFrame' (a nil value)
Time: Mon Sep  5 14:34:00 2022
Count: 1648
Stack: Interface\AddOns\RXPGuides\RXPGuides.lua:738: attempt to call field 'UpdateFrame' (a nil value)
[string "=[C]"]: in function `UpdateFrame'
[string "@Interface\AddOns\RXPGuides\RXPGuides.lua"]:738: in function <Interface\AddOns\RXPGuides\RXPGuides.lua:681>

Locals:

**Comment by SabreValkyrn** [comment] 2022-09-05 15:43
What other lua errors are there? I'd expect more helpful errors to be earlier. If `UpdateFrame` is nil, something else went wrong.

I can't tell what the issue is from that, sorry.

**Comment by babylonlin** [comment] 2022-09-05 16:04
If I track from loading screen, there are some other error:
---------------------------------
Message: Interface\AddOns\RXPGuides\Locale.lua:39: attempt to index field 'words' (a nil value)
Time: Mon Sep  5 18:03:37 2022
Count: 1
Stack: Interface\AddOns\RXPGuides\Locale.lua:39: attempt to index field 'words' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\RXPGuides\Locale.lua"]:39: in function `L'
[string "@Interface\AddOns\RXPGuides\GuideWindow.lua"]:880: in main chunk

Locals: 

-----
not sure if they can help further

**Comment by SabreValkyrn** [comment] 2022-09-05 16:22
> attempt to index field 'words' (a nil value)

This was a problem with 4.2.10 and fixed in 4.2.11 (per Discord from German users). Are you sure you're on 4.2.11?

**Comment by babylonlin** [comment] 2022-09-05 16:59
You are right. After downloading 4.2.11 from github, the problem is solved. The last file is named with "RXPGuides-latest-wrath.zip" from website and thought it must be 4.2.11, but in this case not. 

Thanks

**Closed** 2022-09-05 17:01 UTC
